version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "daily"

  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
